Feature/cria estrutura pagina
OpenDevUFCG/poscomp pull request #18
Opened 2019-07-24 15:27 UTC by lucasmedeiros

Closes #4 

Esta PR adiciona o "esqueleto" da SPA. Estou iniciando essa PR como Draft, pois gostaria de abrir um espaço para discussão a respeito da organização de diretórios, como vamos montar o layout (uso de **grid** ou **flexbox**), e outras questões que vocês podem levantar.

2019-07-24 15:37 UTC, pedroespindula commented
Ao meu ver, deve-se usar CSS Grid sempre seguindo esse formato de definição do grid:

```css
.grid-generico {
  display: grid;
  grid-template-areas:
    'area1 area2';
  grid-template-columns: 1fr 5fr;
  grid-template-rows: 1fr;
}
```

A organização de diretorios está boa mas acredito que o Header seria um componente a parte do Content que estaria dentro do App.

2019-07-24 15:40 UTC, pedroespindula requested changes

2019-07-24 15:40 UTC, pedroespindula commented on src/components/app/App.js
> +
Remover linha em branco

2019-07-24 15:40 UTC, pedroespindula commented on src/components/app/content/Content.js
> +
Remover linha em branco

2019-07-24 18:02 UTC, lucasmedeiros commented
@pedroespindula Feito! Também modifiquei o layout para `flexbox`, visando uma melhor manutenibilidade futura.

2019-07-24 21:31 UTC, ivynasantino commented
Gostei da estrutura dos componentes e até então só tive experiência de desenvolvimento com flex, não sou a melhor pessoa para apontar pós e contras entre as duas ferramentas. Outro ponto, depois das modificações, está dando falha na compilação :'(, está dando essa mensagem: 

*./src/components/render/KatexRender.js
Module not found: Can't resolve 'katex' in '/home/ivyna/Documentos/opendev/poscomp/src/components/render'*

2019-07-24 22:02 UTC, lucasmedeiros commented
@ivynasantino Que estranho, aqui tá de boas. Tu deu `yarn install` novamente depois que @pedroespindula fez o componente renderizador de LaTeX?

2019-07-24 22:13 UTC, ivynasantino commented
Deu certo aqui \o/ Agora o que vocês acham, quando colocarmos os cards, recuar um pouco a página no campo direito?

2019-07-24 22:13 UTC, ivynasantino submitted a review, later dismissed

2019-07-25 20:07 UTC, pedroespindula approved these changes

2019-07-25 22:44 UTC, ivynasantino approved these changes

2019-07-25 23:31 UTC, alvesmatheus approved these changes

2019-07-25 23:33 UTC, merged