Adiciona questão 35 da prova de 2018 e sua solução
OpenDevUFCG/poscomp pull request #27
Opened 2019-07-26 18:22 UTC by alvesmatheus

Fixes #25 

**Descrição do bug/feature:**
Ausência de questões e soluções.

**Solução adotada:**
Adicionei a questão 35 da prova de 2018 e a solução que produzi para a mesma.

**TODO:**
N/A

2019-07-27 21:54 UTC, ivynasantino requested changes

2019-07-27 21:54 UTC, ivynasantino commented on src/lib/provas/2018/35.json
> +        "C": "F – V – F.",
Nessa letra a sequência correta é esta :)
```suggestion
        "C": "F – V – V.", 
```

2019-07-29 16:58 UTC, pedroespindula approved these changes

2019-07-30 23:05 UTC, ivynasantino approved these changes

2019-07-31 15:23 UTC, lucasmedeiros approved these changes

2019-07-31 15:29 UTC, merged