Cria esqueleto da sidenav responsiva
OpenDevUFCG/poscomp pull request #31
Opened 2019-08-10 16:13 UTC by lucasmedeiros

Relacionada a issue #15 

**Descrição do bug/feature:**
Precisava-se da criação de um esqueleto para a sidenav, onde ficariam os filtros das questões do POSCOMP.

**Solução adotada:**
Inicialmente, refatorei o modelo que já se tinha para que possamos trabalhar com as rotas. Minha escolha pelo `BrowserRouter` se deu porque a aplicação, a meu ver, não se encaixa como uma aplicação de uma única página estática, e vamos precisar da API `history`.

Depois da refatoração, criei um esqueleto responsivo de sidenav, onde ficarão os futuros filtros.

**Imagens de ilustração:**
![image](https://user-images.githubusercontent.com/19390820/62824155-74186d80-bb70-11e9-8e2a-cb6ee831ad0c.png)
*Visualização da página no browser*

![image](https://user-images.githubusercontent.com/19390820/62824165-8eeae200-bb70-11e9-8786-bd588ba4d5df.png)
![image](https://user-images.githubusercontent.com/19390820/62824169-94e0c300-bb70-11e9-95ff-e8f3371857f6.png)
*Visualização da página no celular*

**TODO:**
N/A

2019-08-11 00:13 UTC, ivynasantino submitted a review, later dismissed

2019-08-11 18:54 UTC, lucasmedeiros commented
ping @pedroespindula

2019-08-13 16:28 UTC, pedroespindula requested changes

2019-08-13 16:28 UTC, pedroespindula commented on src/components/app/App.css
> +  min-height: 100%;
Porque foi mudado para `min-height`?

2019-08-13 16:28 UTC, pedroespindula commented on src/components/header/PageHeader.js
> +      <div className="header-toggle-button">
Essa `div` é realmente necessaria?

2019-08-13 16:28 UTC, pedroespindula commented on src/components/header/PageHeader.js
> +      <div className="header-title">
E esta?

2019-08-13 16:28 UTC, pedroespindula commented on src/components/header/PageHeader.js
> +        <div>Lorem ipsum dolor sit amet</div>
Porque foi usada uma div? Poderia ser outra tag?

2019-08-13 16:28 UTC, pedroespindula commented on src/components/sidenav/NavContent/NavContent.css
> +.side-nav-content p {
Colocar numa classe ao invés de usar seletores

2019-08-13 16:28 UTC, pedroespindula commented on src/components/sidenav/PageSideNav.js
> +      <NavContent />
Esse componente `NavContent` é necessário?

2019-08-13 16:28 UTC, pedroespindula commented on src/pages/main/Main.js
> +      <section className="pageContent">
O `pageContent` não deveria englobar o Header

2019-08-13 16:28 UTC, pedroespindula commented on src/components/app/App.css
> +  outline: 0;
Essa propriedade não deve ser definida para todos os elementos. Veja o porquê [aqui](http://www.outlinenone.com/)

2019-08-13 16:28 UTC, pedroespindula commented on src/components/app/App.css
> +  box-sizing: border-box;
Acredito que essa propriedade não deva ser colocada em todos os elementos.

2019-08-13 16:28 UTC, pedroespindula commented on src/components/app/App.css
>  }
```suggestion
  width: 100%;
}
```

2019-08-13 16:28 UTC, pedroespindula commented on src/components/app/App.js
>      <div className="App fill-container" >
A classe `App` não existe mais

```suggestion
     <div className="fill-container" >
```

2019-08-13 17:09 UTC, lucasmedeiros commented on src/components/header/PageHeader.js
> +        <div>Lorem ipsum dolor sit amet</div>
Sim, mas isso ainda não foi implementado de fato, tá só como esqueleto nesse caso

2019-08-13 17:11 UTC, lucasmedeiros commented on src/components/app/App.css
> +  min-height: 100%;
Coloquei `min-height` porque o elemento não estava expandindo quando o conteúdo ultrapassava

2019-08-13 17:27 UTC, lucasmedeiros commented on src/components/sidenav/PageSideNav.js
> +      <NavContent />
Sim, porque eu percebi que à medida em que os filtros forem crescendo, pode ficar meio grandinho... Achei que ficaria mais organizado caso já quebrasse logo.

2019-08-13 17:39 UTC, lucasmedeiros commented on src/components/header/PageHeader.js
> +      <div className="header-toggle-button">
Sim, para que eu possa controlar a visibilidade no CSS.

2019-08-13 17:40 UTC, lucasmedeiros commented on src/components/header/PageHeader.js
> +      <div className="header-toggle-button">
Não me sinto tão confortável trabalhando com nomes de componentes no CSS, e sim com classes kkkkk

2019-08-13 17:42 UTC, lucasmedeiros commented on src/components/header/PageHeader.js
> +      <div className="header-title">
Sim, para que se comporte da maneira esperada a partir do uso do `flex` no parent.

2019-08-13 17:44 UTC, lucasmedeiros commented on src/pages/main/Main.js
> +      <section className="pageContent">
Eu não dei um nome muito bom pra essa classe mesmo, mas é que se não englobar, não vai se encaixar no comportamento esperado pelo uso do `flex`.

2019-08-13 17:47 UTC, lucasmedeiros commented
@pedroespindula Ajustei e respondi alguns comentários que você fez. Dá uma olhada

2019-08-14 00:21 UTC, pedroespindula commented on src/components/header/PageHeader.js
> +      <div className="header-toggle-button">
Uhum, mas tipo, tu podia passar essa classe por prop pra o componente tipo:

```html
<ToggleButton className="header-toggle-button"/>
```

Ai la dentro do componente tu fazia:

```html
<button className={props.className}/>
```

Que ai tu torna teus componentes personalizáveis por classes sem precisar de uma div wrapper

2019-08-14 00:21 UTC, pedroespindula commented on src/components/header/PageHeader.js
> +      <div className="header-title">
Acredito que o uso de grid nesse caso seria mais adequado então.

2019-08-14 00:22 UTC, pedroespindula commented on src/pages/main/Main.js
> +      <section className="pageContent">
Acredito que este caso também seria melhor usar grid

2019-08-14 18:51 UTC, lucasmedeiros commented on src/components/header/PageHeader.js
> +      <div className="header-title">
Eu tentei fazer por `grid` e pra atingir o mesmo comportamento, teria que adicionar muito mais coisa e deixaria o código mais sujo, a meu modo de ver. Creio que seja melhor deixar assim, para que o código seja mais limpo mesmo.

2019-08-14 19:05 UTC, lucasmedeiros commented on src/pages/main/Main.js
> +      <section className="pageContent">
Assim como a sugestão anterior, eu também acho meio problemático trocar pra `grid` nesse caso, por causa que o código também ficaria sujo por causa da responsividade e `flex` trabalha melhor para esses casos, já que estamos falando de elementos que têm apenas "uma dimensão", e não se comporta como malha.

2019-08-26 12:30 UTC, lucasmedeiros commented
ping @pedroespindula

2019-10-02 12:12 UTC, pedroespindula approved these changes

2019-10-02 12:12 UTC, merged